### ISSUE TITLE
hxcpp debugging tools: hxScout / vscode -- pre-recorded /w remote q&a?

### ISSUE THREAD

**Issue by jcward** [silexlabs/wwx2016#22]
Hi guys,

I'm interested in presenting the debugging tooling I've been working on for the past year and a half-ish, from hxScout to the VSCode plugins (hxcpp debugging). But there's likely no way I can make it to Paris for the conference.

Would a pre-recorded session followed by live question/answer (twitch or chat) be feasible? I suggest pre-recorded because live/remote seems too error prone. As for duration, I could likely do either 15 or 40 minutes - the difference would be the amount of detail and Q&A time.

Thoughts?

**Comment by clemos** [comment]
Hi Jeff,
While the topic is very interesting, we're not really used to accept remote / recorded sessions at WWX.
We'll discuss this with the rest of the team, and come back to you very soon to give you a definitive answer.
Best,
Clément

**Comment by lexoyo** [comment]
:-1: for remote sessions (sorry jeff :-/)

**Comment by jcward** [comment]
Maybe another time. Cheers.

**Comment by clemos** [comment]
Yes, sorry for the delay.
We've discussed this issue a lot, because there are quite some major members of the community who seemed interested in giving a remote talk.
Unfortunately, from the attendees' perspective, I think it would be frustrating, if not boring, and anyway quite disappointing, given some of them come from the other side of the planet...

There are also technical issues in hosting a remote talk with potential Q&A from the WWX audience, broadcasted to a remote audience, etc. 
It's probably doable, but since we have been very criticized about the quality of WWX live stream, we're trying to stick to a simple, qualitative setup.

So we're sorry, but WWX won't host remote talks ;)

**Comment by jcward** [comment]
@clemos no worries, I agree, seems best.
