### ISSUE TITLE
Workshop: Ufront

### ISSUE THREAD

**Issue by ngrebenshikov** [silexlabs/wwx2016#24]
It would be great to have a Ufront workshop on the WWX. Is there anybody who can and want to conduct it?

**Comment by ngrebenshikov** [comment]
And is there time for it on the conference?

**Comment by andyli** [comment]
@kevinresol Any chance for you to come to wwx? ;)

**Comment by kevinresol** [comment]
@andyli I think I have to decline your kind invitation, mainly due to lack of travelling budget. Also I don't think I am capable of holding a workshop, given that I am a good speaker :stuck_out_tongue:  and I am not really an expert of ufront. There are still a lot of features of ufront I have never touched. I rather teach in form of writing, I will try to write down all I know [here](https://github.com/kevinresol/ufront-nodejs-guide/).

**Comment by andyli** [comment]
No one is born to be a good speaker, we just have to gain experience by doing it more often. And to be honest I'm not good at speaking either...
And I believe you already know much about ufront. At least you are able to write it up.
For travelling budget, HF may sponsor active community members to attend wwx. I think it happened for the previous year. If you make your mind up, we can ask Nicolas to see if it is possible.

**Comment by andyli** [comment]
Don't have any pressure though. If you insist not doing it this time, we're still happy to read your ufront guide and wish to see on stage in the future : )

**Comment by kevinresol** [comment]
Hm.. I will sit back and think about it.

What do you guys expect in a (ufront) workshop?

**Comment by ngrebenshikov** [comment]
I'm not familiar with Ufront at all. I'll be happy to try it. May be to create a simple site from scratch.
