### ISSUE TITLE
Kha Returns

### ISSUE THREAD

**Issue by clemos** [silexlabs/wwx2016#26]
Hi @RobDangerous

Could you please fill and / or correct the following infos ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks !

---
#### Job title

CTO at KTX Software Development
#### Biography

Robert does development work for serious games and gaming related research projects. He’s also regurlarly teaching at different universities. He discovered Haxe during new years eve when everybody else was partying and it was love at first project. 
#### Talk’s title

Kha returns
#### Talk’s focus & description

.
#### Links

.

**Comment by RobDangerous** [comment]
### Job title

CTO at KTX Software Development

### Biography

Robert does development work for serious games, less serious games and gaming related research projects. He is best known for creating Kha, a Haxe based cutting edge multimedia framework.

### Talk’s title

Kha Returns

### Talk’s focus & description

After shaking up the world at WWX2015 Kha returns to Paris with a heap of new features. I will report about the progress since last year which focuses on new graphics features, performance improvements and Kha's new IDE Kode Studio.

### Links

http://kha.tech

**Comment by ibilon** [comment]
Hey @RobDangerous, would it be ok for us to upload your presentation (http://robdangero.us/wwx2016/#/) on the wwx website?

**Comment by RobDangerous** [comment]
Yes, ok for me. Fetch it from https://github.com/RobDangerous/KhaReturns

**Comment by ibilon** [comment]
Thanks.
