### ISSUE TITLE
 JTransc: Java and Kotlin everywhere through Haxe

### ISSUE THREAD

**Issue by clemos** [silexlabs/wwx2016#27]
Hi @soywiz

Could you please fill and / or correct the following infos ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks !

---
#### Job title

Front Tech Lead at Akamon
#### Biography

.
#### Talk’s title

 JTransc: Java and Kotlin everywhere through Haxe
#### Talk’s focus & description

.
#### Links

.

**Comment by clemos** [comment]
Hey @soywiz,
Can you please give us these infos so we can announce your talk ?
Thanks in advance

**Comment by soywiz** [comment]
Woops. Sorry, I missed this!

## Biography:

Short:

A restless programmer interested in videogames, opensource, emulators and productivity.

Longer:

Interested in programming and videogames since I was a child, I grew up grateful to people that shared their code before I had direct access to the Internet.

After that I started to create tons of opensource projects and libraries in several different languages. Most of them related to videogames, emulators, generic libraries or productivity.

I'm interested in both: backend and frontend development.

## Talk’s focus & description:

In this talk I'm going to explain what is JTransc, how does it works and why I did it. Also I will explain how to integrate with haxe libraries and how to embed plain haxe code. I will show the current workflow and will talk about the future of the project.

Uncompleted/unpolished points:
- What is JTransc
- How does it works (overview)
- Productivity over writting haxe directly
- Sharing code with java backends
- Why JTransc instead of other alternatives like: GWT, RoboVM, TeaVM, plain kotlin js
- Why target to Haxe
- How to integrate with haxe libraries
- Demos
- Future

## Links:
- http://jtransc.com/
- https://github.com/jtransc/jtransc

**Comment by clemos** [comment]
Hi @soywiz,
Thanks for the infos :)
We would like to schedule a remote rehearsal of your talk, like we do with all speakers.
Please reach me by PM (my email address is on my profile, yours doesn't seem available) so we can set this up quickly.
Best,

**Comment by soywiz** [comment]
I wrote you already (and made my email public in my profile).

**Comment by ibilon** [comment]
Hey @soywiz, would it be ok for us to upload your presentation (https://docs.google.com/presentation/d/1ZnQr8eBPQNvtM_rJIYg8_vA60HbTDGh2gaf9F0SoqHE/edit#slide=id.p) on the wwx website?

**Comment by soywiz** [comment]
Sure :)

**Comment by ibilon** [comment]
Thanks.
