### ISSUE TITLE
WWX16 schedule

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/wwx2016#37]
Hi everyone!

Now that we have all the information about the speeches and lightning talks, here's the soon to be final schedule:
### Friday 27 : Welcoming day & Workshops

| Time | Event |
| --- | --- |
| 2:00pm - 4:30pm | Workshop 1 |
| 4:30pm - 7:00pm | Workshop 2 |
| 7:00pm - 8:00pm | Welcoming Apero |
| 8:30pm - 11:00pm | Welcoming Diner |
### Saturday 28 : Conference day 1

| Time | Event |
| --- | --- |
| 9:00am - 9:30am | Coffee time |
| 9:30am - 10:00am | Intro |
| 10:00am - 10:45am | Justin Donaldson:   The Haxe Lua Target #35 |
| 11:00am - 11:15am | Alexandre Strzelewicz: Networked process manager and micro service architecture |
| 11:20am - 12:05am | Emmanuel Botros:  PISTAHX: type safe, design first, haxe based web api #7 |
| 12:20am - 1:50pm | Lunch break |
| 2:00pm - 2:45pm | Robert Konrad:    Kha Returns #10 |
| 3:00pm - 3:15pm | Dan Korostelev: Using Haxe with Unity3D and node.js #30 |
| 3:20pm - 4:05pm | Cauê Waneck: Unreal.hx: Using Haxe with the Unreal Engine 4 #13 |
| 4:15pm - 4:30pm | Maxim Bekhterev: Jive UI for mobile platforms #6 |
| 4:40pm - 5:10pm | Break 30 min |
| 5:10pm - 5:55 | Hugh Sanderson: Hxcpp #33 |
| 6:10pm - 6:55 | Hector Espeso: FlashDevelop #17 |
| 7:00pm - 7:15pm | Josefiene Petrosa: Haxe Foundation |
| 8:30pm - 12:00pm | Party time |
### Sunday 29 : Conference day 2

| Time | Event |
| --- | --- |
| 11:00am - 12:30am | Brunch |
| 12:30am - 1:15pm | Ian Harrigan: HaxeUI Version 2 - Multi-platform, Multi-framework UI #12 |
| 1:30pm - 2:15pm | Francis Bourre: hexMachina framework #14 |
| 2:30pm - 3:00pm | Break 30 min |
| 3:00pm - 3:45pm | David Peek: Haxe React #11 |
| 4:00pm - 4:15pm | Alex Hoyau: Secret Talk |
| 4:30pm - 5:15pm | Carlos Ballesteros Velasco: JTransc: Java and Kotlin everywhere through Haxe #27 |
| 5:15pm - 5:45 | Break 30 min |
| 5:45pm - 6:30 | Making the most of Haxe #39 |
| 6:30pm - 7:15 | Andy Li: Highway to the external world: Generate externs programmatically #28 |
| 7:15 - 7:30 | Outro |
### Monday 30 : Workshop & Haxathon

| Time | Event |
| --- | --- |
| 10:00am - 12:30am | Workshop 3 |
| 12:30am - 2:00pm | Lunch |
| 2:00pm - 6:00pm | Haxathon (to be defined) |

If you see any incoherence in it, please let us know ASAP. We'll publish it on the website (and make it final) before the end of the week.

**Comment by mebyz** [comment]
small mistake, could you please correct my project's name please ? ( on the wwx website too if possible :) )

it has been renamed to "PISTAHX : type safe, design first, haxe based web api"
http://www.pistahx.io

thanks a lot !

**Comment by JbIPS** [comment]
Done! And looks like @ibilon is updating the website

**Comment by back2dos** [comment]
I would like to propose that the schedule be reordered somewhat. Let me explain.

There is always talk about making Haxe get out of the game development niche. There way the schedule is organized now, I think it puts game-centric talks into the best slots (i.e. Saturday afternoon). If we see the conference as an opportunity to shine a light on other aspects of Haxe, we should put other talks there. 

Outside game development, the pressure is much higher to integrate well with the native ecosystems (UI in particular). Every time I pitch Haxe to other devs, they ask me about this. Both #12 and #28 talk about that - #12 because HaxeUI 2 sports native UIs. If the guys from haxe-react can showcase React Native support, then #11 also touches that point.

I don't mean to say that talk X is generally more important than talk Y. In a community as diverse as ours, everyone will have a different opinion on that anyway. But many community members struggle with selling Haxe. I would like to see as many of them go home with confidence in Haxe's rapidly growing ability to seamlessly embed itself into native contexts.

**Comment by JbIPS** [comment]
I like the idea! So we switch Saturday afternoon (from Robert to Josefiene) with the actual Sunday. If everybody's ok with that we'll announce the official/final/static inline schedule on the website in a few days.

**Comment by sebpatu** [comment]
who is doing the intro? is this Nicolas? as it does not seems to be a year feedback from him, llike every year.
thanks

**Comment by JbIPS** [comment]
As every edition, a member of Silex Labs will do the opening speech. AFAIK Nicolas won't be present this year so we're working with the Haxe Foundation to find a speaker for their slot (actually Josefiene).

**Comment by ibilon** [comment]
The schedule on the first post was changed,
please look at http://wwx.silexlabs.org/2016/#schedule for the latest version.

**Comment by sebpatu** [comment]
thanks for the reply.
just one thing: why still having a talk about flashdevelop, and not haxedevelop?

**Comment by back2dos** [comment]
@sebpatu Good point, but I think #17 might be better suited to discuss it ;)
