### ISSUE TITLE
free event or not?

### ISSUE THREAD

**Issue by andyli** [silexlabs/wwx2016#38]
Stated in the "About this project" section of the [ulule page](https://www.ulule.com/wwx2016/):

> The tickets for the conference will be free, as per our partnership with Mozilla, and we will start the ticket reservation once the first goal is achieved.

But now the [eventbrite registration page](http://www.eventbrite.fr/e/world-wide-haxe-conference-2016-wwx2016-tickets-24926284187) doesn't make it clear that it is free and there is no option to register without paying fee. I understand it would be great to get some more funds, but it sounds like cheating.

I invited my girl friend and her bother to wwx since they're interested in haxe too. They contributed, but it was less then EUR 100 (just because the air tickets are already expensive for Hong Kongers). They are now confused by the email saying they need to buy tickets. I'm fine to pay for their tickets, and I appreciate the effort you did to make wwx happens, but I just worry it doesn't sound consistent  to outsiders.

It would be great if you can clarify the matter with an update email and revise the description in the eventbrite page.

**Comment by antosilex** [comment]
Hi Andy,

We are very sorry for the misunderstanding, First of all we will of course add your girlfriend and her brother to the attendees list (thanks for giving me their name and email address).

Then we'd like to explain this last minute change:
As you may know the Crowd funding campaign didn't achieve the final goal with the stream and the production of the videos after the conference.

We though we would achieve this goal as last year because we've contacted last year's sponsors one month before launching the Crowd funding camapaign and they seemed motivated to sponsorized, however most of them changed their minds during the campaign.

Therefore at the end of the CF Campaign we were even far from the second goal.

We tried to find new sponsor and to cancel the free saturday night party to see if we could make the video, but it was still not sufficient, in spite of all the extra amount of work we've done.

So we decided to sell more tickets to try to finish as close as we can to the amount necessary to make a great conference even for the people who can't come and who wanted the video.

Just to let you know last year only one of the eighteen free registered people came to the conference, so we thought it was worth to wait the last moment to allow people to register for free. 

We'll try to clarify this issue officially very soon.

Best

**Comment by andyli** [comment]
Thanks for the reply!

So, have we achieved the amount for live streaming and video archive yet? The email I received says they will be provided since you have found new sponsors. But from your reply above, it sounds like it is still not enough. Anyway, in my opinion, the stream and the video are much more important then the food. As a participant, I totally don't mind no free lunch/dinner/party will be provided.

Also, I hope the money being spent on each item will be public, just like how the organizing process is transparent in this github repo (big thumb up for this!). I totally trust SilexLabs will spend the money to the right things, but still, donors deserve knowing where their money went at the end.

Thanks again for all the hard works!

**Comment by ibilon** [comment]
The free option was explained on eventbrite, closing.
