### ISSUE TITLE
Haxe Foundation speech and remote talks

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/wwx2016#42]
Hi everyone,

We got a request from @ncannasse to make the Foundation talk remotely (and recorded). We'd like to know your opinion on that and maybe a bit more information on the talk (like the other ones).

IMO, I'd prefer a live in-person speech so there could be a dialog with the attendees after the talk and I hope someone like @Merelleya @andyli or @Simn could do it.

Thoughts everyone?

**Comment by clemos** [comment]
I also don't really see the point of coming to Paris to see a remote, pre-recorded speech.

**Comment by markknol** [comment]
If it is mixed in some kind of awesome trailer full of spectacular special fx it might be interesting, something like this:
_CEO APPEARS_; WE ADDED A NEW TARGET **BOOM! FLASH! SFX** WE ADDED THIS FEATURE **PARTICLES!**  WE ADDED ANOTHER TARGET **SWOOSH MILLION PARTICLES APPEAR!** WE ELEMINATE ALL DEAD CODE **HEAVY DRUM SOUNDS** OH, ONE MORE THING **PRESENT MAGICAL NEW FEATURE** _CEO DISAPPEARS_

**Comment by andyli** [comment]
I thought the day 1, 7:00pm - 7:15pm slot is reversed for @Merelleya for this HF speech. Apparently  this isn't the same thing?

On the one hand, as an audience, I don't mind to see a remote talk, given Nicolas is the creator of Haxe, and is pretty much _the_ head of HF.

On the other hand, I think @Simn should give a talk. I mean, his contribution quality and quantity to the compiler is second to none in these years. His should be recognized by more Haxers :)

For myself, I've my own talk to prepare. It would be a bit stressful for me to prepare another one now.

**Comment by back2dos** [comment]
Generally speaking, I am strongly opposed to having remote/prerecorded talks. There's no need to gather everyone in one place to do that. We might as well do the conference online then ...

Maybe an exception is in order, because after all, Nicolas is the father of Haxe. 

There's is something that I need to get off my chest: Had we known about his long-standing plans to be on the other side of the planet when we hold our yearly conference, I would have thrown around what weight I have to move the conference so that he can attend. But we only found this out when the room was booked, the date was set and we were getting ready to announce. Personally, I find this quite upsetting, because it leaves us in a bad position, that could have been avoided by some minimal communication on Nicolas' part. Instead, we're left with this dilemma. It would be sad to have a conference without him addressing the audience, but it would be equally sad if the keynote were something you get "Every Friday - 1:30pm (Paris time)".

The HF was created - among other things - so that Haxe would no longer be perceived as a one-man-show. Therefore, I would find it would send the right sign if someone else could deliver the keynote. Ideally, it would include a short, prerecorded video / live stream (?) with Nicolas, so we get the best of both worlds. FWIW, that would be my preferred solution.

As for @Simn giving a talk, it would be awesome. Last I asked him about that, he didn't seem to like the idea and said something along the lines of "I wouldn't know what to talk about" - which sounds like a very bad excuse. But if his mind has changed, then I would love to see that happen.

Personally I was expecting @Merelleya to speak on behalf of the Foundation and I was actually looking forward to it. Having someone other than opinionated nerds talk about Haxe always make for a beautiful contrast :D

**Comment by JbIPS** [comment]
@back2dos A live speech including a prerecorded video seems like a good compromise! In fact, it would help us make the right choice if we knew what the Foundation's talk will be about. We're finalizing the schedule and as we say to all the other speakers that didn't fill up their info, we need all of them for Monday or we'll have to cancel it.

As for the slot reserved for @Merelleya, it's a temporary placeholder since we don't even know how long the speech will be. We put it at the end of the day so it wouldn't impact the whole schedule but, again, more info will be mandatory.

**Comment by ncannasse** [comment]
@back2dos FYI, it was indeed a long time planned whole family trip, and I was myself surprise when Silex announced the dates without being contacted first about being available. But it's ok, since they organize the conference. `</nopolemicplease>`

I have to check where exactly I will be during this week-end, I'm afraid I won't be at my stepparents home so won't have internet access for live streaming. Hence my proposal for a recorded talk, which I would advise anyway because of the potential for technical/streaming issues. I was thinking I would be able to live answer questions after the talk, but this also depends on having internet access, I'll check and tell you asap.

Regarding the content I was planning to update regarding HF work, and introduce Haxe 3.3 new features (we will have a RC ready for WWX).

I have to discuss with @Merelleya about her talk, I'm not sure which topic she was planning to cover.

**Comment by Simn** [comment]
Alright, originally I planned not to attend WWX this year, but some circumstances changed so I'll be there after all. I'll talk to Nicolas regarding the foundation talk/keynote next week. It's going to be a bit short-term, but I usually prepare my talks on the train to the venue anyway.

**Comment by ibilon** [comment]
@Simn at this point can you confirm you'll do it, even if you don't know yet what you would talk about?

**Comment by ncannasse** [comment]
I just saw the schedule was published with neither my talk or Simon one,
which I find very annoying given that HF sponsor WWX and that we were not
informed that the decision was made to remove our talks. There's a 15 min
slot for Fiene but it's far from enough to for instance present new 3.3
features...

So find a way asap to put a back a 30 or 45 minutes talk after the Intro,
since either me (recorded) or Simon deliver the talk at this slot.

PS: I'll be away from the net in the upcoming 2 days

**Comment by ibilon** [comment]
I'm the one who commited the schedule on the website, we did not remove your talk, I simply had nothing to include. Neither a speaker, a title nor a length. (the last one being absolutely essential to scheduling)
WWX being very soon we just had to put something online, even if we then modify something.

> which I find very annoying

Well we had to open this issue after two weeks of emails asking for the required details to schedule the talk so don't be.

Please give us a title/length/speaker (name + picture) and we'll do all we can to put it in the schedule ASAP.
And then: Job title / occupation, Biography, Talk’s focus & description, Links relevant about you and your talk.
Just like **every** talk.

> PS: I'll be away from the net in the upcoming 2 days

Is there a way you can delegate? WWX is really close.

**Comment by Simn** [comment]
I'll do the talk, let me know if you need anything. As for the schedule, just call it keynote I guess.

**Comment by ibilon** [comment]
@Simn thanks, can you send a picture of you?
How long do you want 15, 30, 45 minutes?

The temporary slot we added for HF is the last of Saturday,
having a "end of the day keynote" is not unheard of but tell me if you want to change the talk name.

**Comment by Simn** [comment]
I'll have to go take pictures this week, I genuinely don't have any recent ones. We took some last WWX but I don't know what happened to these. Maybe @lexoyo knows?

Keynote at the end of the day sounds really awkward, but I understand you don't want to mess up the schedule at this point (I wasn't involved in any prior discussion about this, so I don't know why no keynote place was reserved from the start). In that case we should label the talk differently. I'll look into it tomorrow and let you know.

As for the length, I certainly have enough material for 45 minutes, but I could do with 30 if it's better for the schedule.

**Comment by JbIPS** [comment]
Just so we're clear, how many talks will you do? Do we keep one lightning and one full sized? Will they be merged into one 45 minute long?

**Comment by Simn** [comment]
One talk

**Comment by Simn** [comment]
@ibilon: "haxe-dev: Tales from within"

**Comment by ibilon** [comment]
@Simn thanks, modified the talk name and speaker on the website, the talk is scheduled for 45 minutes.

**Comment by Simn** [comment]
@ibilon:

![dsc_9901-5](https://cloud.githubusercontent.com/assets/634365/15506847/6e961662-21c9-11e6-830c-5c911643bee3.jpg)

**Comment by ibilon** [comment]
@Simn great, you are now on the speaker list.
Last things we need are biography and talk’s description.

Btw maybe you could add this picture on the who is who page of haxe.org ;)

**Comment by Simn** [comment]
Desc:

> Even after over 10 years, the Haxe Compiler and its related technologies are in constant development. This is made possible by a strong development community which has grown over the years and continues to grow.
> 
> This talk explores what happened since WWX 2015, and who made it happen. While there's a natural technical focus given the subject matter, it is also going to highlight some interpersonal aspects of open source development. Expect a mixture of development anecdotes and compiler-related tech-talk.

Bio:

> Simon has been the main maintainer of the Haxe Compiler for several years. He enjoys investigating and solving problems, especially in collaboration with others.

**Comment by ibilon** [comment]
Thanks for being so quick, fully on the website now.

**Comment by ibilon** [comment]
Hey @Simn, couldn't find your presentation online, could you upload it? (or send us a link if I just missed it)
Also would it be ok for us to upload it on the wwx website?

**Comment by Simn** [comment]
It's over at https://github.com/ncannasse/hxslides/tree/master/www. You'll need a few files from there (css, js). Feel free to use it any way you like and let me know if you need anything else.

**Comment by ibilon** [comment]
Thanks.

**Comment by Simn** [comment]
You're welcome!

Note that you didn't need most of the images you added.
